# Generated by Django 4.2.13 on 2026-07-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(max_length=50, verbose_name='配置名称')),
                ('pay_type', models.SmallIntegerField(verbose_name='支付类型')),
                ('app_id', models.CharField(blank=True, max_length=100, verbose_name='应用ID')),
                ('mch_id', models.CharField(blank=True, max_length=100, verbose_name='商户号')),
                ('api_key', models.CharField(blank=True, max_length=200, verbose_name='API密钥')),
                ('notify_url', models.CharField(blank=True, max_length=200, verbose_name='回调地址')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '支付配置',
                'verbose_name_plural': '支付配置',
                'db_table': 'payment_config',
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_no', models.CharField(max_length=50, unique=True, verbose_name='支付单号')),
                ('order_id', models.IntegerField(verbose_name='订单ID')),
                ('pay_type', models.SmallIntegerField(choices=[(1, '微信支付'), (2, '支付宝'), (3, '余额支付')], verbose_name='支付方式')),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支付金额')),
                ('pay_state', models.SmallIntegerField(choices=[(0, '未支付'), (1, '支付成功'), (2, '支付失败')], default=0, verbose_name='支付状态')),
                ('trade_no', models.CharField(blank=True, max_length=100, verbose_name='第三方交易号')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '支付订单',
                'verbose_name_plural': '支付订单',
                'db_table': 'payment_order',
            },
        ),
    ]
