# Generated by Django 4.2.13 on 2026-07-19 22:25

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='头像')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='昵称')),
                ('gender', models.SmallIntegerField(choices=[(0, '保密'), (1, '男'), (2, '女')], default=0, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('wechat_openid', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='微信OpenID')),
                ('wechat_unionid', models.CharField(blank=True, max_length=100, null=True, verbose_name='微信UnionID')),
                ('user_level_id', models.IntegerField(default=1, verbose_name='会员等级ID')),
                ('user_points', models.IntegerField(default=0, verbose_name='积分')),
                ('user_money', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='余额')),
                ('user_parent_id', models.IntegerField(default=0, verbose_name='推荐人ID')),
                ('user_invite_code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='邀请码')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='system.userrole', verbose_name='角色')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
                'ordering': ['-id'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=50, verbose_name='等级名称')),
                ('level_discount', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='折扣率')),
                ('min_points', models.IntegerField(default=0, verbose_name='所需最低积分')),
                ('max_points', models.IntegerField(default=0, verbose_name='所需最高积分')),
                ('level_icon', models.ImageField(blank=True, null=True, upload_to='users/levels/', verbose_name='等级图标')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认等级')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户等级',
                'verbose_name_plural': '用户等级',
                'db_table': 'user_level',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='UserPointsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='积分变动')),
                ('points_type', models.SmallIntegerField(choices=[(1, '订单获得'), (2, '签到获得'), (3, '消费扣除'), (4, '后台调整')], verbose_name='积分类型')),
                ('description', models.CharField(max_length=200, verbose_name='说明')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_history', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '积分历史',
                'verbose_name_plural': '积分历史',
                'db_table': 'user_points_history',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.SmallIntegerField(choices=[(1, '系统消息'), (2, '订单消息'), (3, '活动消息'), (4, '物流消息')], default=1, verbose_name='消息类型')),
                ('title', models.CharField(max_length=100, verbose_name='消息标题')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户消息',
                'verbose_name_plural': '用户消息',
                'db_table': 'user_message',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_ip', models.GenericIPAddressField(verbose_name='登录IP')),
                ('login_device', models.CharField(blank=True, max_length=50, verbose_name='登录设备')),
                ('login_os', models.CharField(blank=True, max_length=50, verbose_name='操作系统')),
                ('login_browser', models.CharField(blank=True, max_length=50, verbose_name='浏览器')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '登录历史',
                'verbose_name_plural': '登录历史',
                'db_table': 'user_login_history',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignee', models.CharField(max_length=50, verbose_name='收货人')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('province', models.CharField(max_length=50, verbose_name='省')),
                ('city', models.CharField(max_length=50, verbose_name='市')),
                ('district', models.CharField(max_length=50, verbose_name='区/县')),
                ('address', models.CharField(max_length=200, verbose_name='详细地址')),
                ('zipcode', models.CharField(blank=True, max_length=10, verbose_name='邮编')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认地址')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '收货地址',
                'verbose_name_plural': '收货地址',
                'db_table': 'delivery_address',
                'ordering': ['-is_default', '-id'],
            },
        ),
    ]
