# Generated by Django 4.2.13 on 2026-07-19 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='商品ID')),
                ('product_item_id', models.IntegerField(verbose_name='商品SKU ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('product_image', models.CharField(blank=True, max_length=500, verbose_name='商品图片')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('is_checked', models.BooleanField(default=True, verbose_name='是否选中')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
                'db_table': 'cart',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='订单号')),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品总金额')),
                ('freight_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='运费')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='优惠金额')),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实付金额')),
                ('status', models.SmallIntegerField(choices=[(0, '待支付'), (1, '待发货'), (2, '待收货'), (3, '已完成'), (4, '已取消'), (5, '退款中'), (6, '已退款')], default=0, verbose_name='订单状态')),
                ('pay_type', models.SmallIntegerField(blank=True, choices=[(1, '微信支付'), (2, '支付宝'), (3, '余额支付'), (4, '货到付款')], null=True, verbose_name='支付方式')),
                ('consignee', models.CharField(max_length=50, verbose_name='收货人')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('province', models.CharField(max_length=50, verbose_name='省')),
                ('city', models.CharField(max_length=50, verbose_name='市')),
                ('district', models.CharField(max_length=50, verbose_name='区/县')),
                ('address', models.CharField(max_length=200, verbose_name='详细地址')),
                ('user_remark', models.TextField(blank=True, verbose_name='买家备注')),
                ('admin_remark', models.TextField(blank=True, verbose_name='管理员备注')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('ship_time', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('cancel_time', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'order',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='商品ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('product_image', models.CharField(max_length=500, verbose_name='商品图片')),
                ('product_item_id', models.IntegerField(verbose_name='SKU ID')),
                ('sku_name', models.CharField(max_length=200, verbose_name='SKU名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='小计')),
                ('is_comment', models.BooleanField(default=False, verbose_name='是否已评价')),
                ('is_return', models.BooleanField(default=False, verbose_name='是否退货')),
            ],
            options={
                'verbose_name': '订单商品',
                'verbose_name_plural': '订单商品',
                'db_table': 'order_item',
            },
        ),
        migrations.CreateModel(
            name='OrderLogistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('express_company', models.CharField(blank=True, max_length=50, verbose_name='物流公司')),
                ('express_no', models.CharField(blank=True, max_length=50, verbose_name='物流单号')),
                ('express_time', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('logistics_info', models.TextField(blank=True, verbose_name='物流信息(JSON)')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '订单物流',
                'verbose_name_plural': '订单物流',
                'db_table': 'order_logistics',
            },
        ),
        migrations.CreateModel(
            name='OrderReturnReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100, verbose_name='退货原因')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '退货原因',
                'verbose_name_plural': '退货原因',
                'db_table': 'order_return_reason',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='OrderReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_no', models.CharField(max_length=50, unique=True, verbose_name='退款单号')),
                ('return_type', models.SmallIntegerField(choices=[(1, '仅退款'), (2, '退货退款')], verbose_name='退款类型')),
                ('return_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='退款金额')),
                ('return_reason', models.CharField(max_length=200, verbose_name='退款原因')),
                ('return_description', models.TextField(blank=True, verbose_name='退款说明')),
                ('return_images', models.TextField(blank=True, verbose_name='凭证图片(JSON)')),
                ('status', models.SmallIntegerField(choices=[(0, '待审核'), (1, '审核通过'), (2, '审核拒绝'), (3, '退货中'), (4, '已完成')], default=0, verbose_name='状态')),
                ('admin_remark', models.TextField(blank=True, verbose_name='管理员备注')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='trade.order', verbose_name='订单')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.orderitem', verbose_name='订单商品')),
            ],
            options={
                'verbose_name': '退货退款',
                'verbose_name_plural': '退货退款',
                'db_table': 'order_return',
                'ordering': ['-created_time'],
            },
        ),
    ]
