# Generated by Django 4.2.13 on 2026-07-19 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=100, verbose_name='活动名称')),
                ('activity_type', models.SmallIntegerField(choices=[(1, '优惠券'), (2, '秒杀'), (3, '拼团'), (4, '砍价'), (5, '满减')], verbose_name='活动类型')),
                ('activity_state', models.SmallIntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已结束'), (3, '已取消')], default=0, verbose_name='活动状态')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('activity_desc', models.TextField(blank=True, verbose_name='活动描述')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '营销活动',
                'verbose_name_plural': '营销活动',
                'db_table': 'activity_base',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(max_length=100, verbose_name='优惠券名称')),
                ('coupon_type', models.SmallIntegerField(choices=[(1, '满减券'), (2, '折扣券'), (3, '兑换券')], verbose_name='类型')),
                ('coupon_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='优惠金额')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最低消费')),
                ('total_quantity', models.IntegerField(verbose_name='总量')),
                ('received_quantity', models.IntegerField(default=0, verbose_name='已领取')),
                ('per_user_limit', models.IntegerField(default=1, verbose_name='限领')),
                ('valid_days', models.IntegerField(verbose_name='有效天数')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '优惠券',
                'verbose_name_plural': '优惠券',
                'db_table': 'coupon',
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_state', models.SmallIntegerField(choices=[(0, '未使用'), (1, '已使用'), (2, '已过期')], default=0, verbose_name='状态')),
                ('order_id', models.IntegerField(blank=True, null=True, verbose_name='订单ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('received_time', models.DateTimeField(auto_now_add=True, verbose_name='领取时间')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.coupon', verbose_name='优惠券')),
            ],
            options={
                'verbose_name': '用户优惠券',
                'verbose_name_plural': '用户优惠券',
                'db_table': 'user_coupon',
            },
        ),
    ]
