# Generated by Django 4.2.13 on 2026-07-19 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('main_image', models.ImageField(upload_to='products/main/', verbose_name='主图')),
                ('images', models.TextField(blank=True, verbose_name='商品图片列表(JSON)')),
                ('description', models.TextField(blank=True, verbose_name='商品简介')),
                ('detail_html', models.TextField(blank=True, verbose_name='商品详情HTML')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='销售价格')),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='市场价格')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='成本价')),
                ('stock', models.IntegerField(default=0, verbose_name='总库存')),
                ('sales_count', models.IntegerField(default=0, verbose_name='销量')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览量')),
                ('favorite_count', models.IntegerField(default=0, verbose_name='收藏量')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('rating_average', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='平均评分')),
                ('state', models.SmallIntegerField(choices=[(0, '下架'), (1, '上架')], default=1, verbose_name='商品状态')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('is_new', models.BooleanField(default=False, verbose_name='是否新品')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热销')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'product',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='品牌名称')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='products/brands/', verbose_name='品牌Logo')),
                ('description', models.TextField(blank=True, verbose_name='品牌描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '商品品牌',
                'verbose_name_plural': '商品品牌',
                'db_table': 'product_brand',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('level', models.SmallIntegerField(default=1, verbose_name='分类层级')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='products/categories/', verbose_name='分类图标')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'product_category',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='规格名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '商品规格',
                'verbose_name_plural': '商品规格',
                'db_table': 'product_spec',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='标签名称')),
                ('color', models.CharField(default='#FF0000', max_length=20, verbose_name='标签颜色')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '商品标签',
                'verbose_name_plural': '商品标签',
                'db_table': 'product_tag',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='规格值')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/specs/', verbose_name='规格图片')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.productspec', verbose_name='所属规格')),
            ],
            options={
                'verbose_name': '商品规格值',
                'verbose_name_plural': '商品规格值',
                'db_table': 'product_spec_value',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=50, unique=True, verbose_name='SKU编码')),
                ('spec_values', models.TextField(verbose_name='规格值(JSON)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/items/', verbose_name='SKU图片')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='成本价')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('sales_count', models.IntegerField(default=0, verbose_name='销量')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品SKU',
                'verbose_name_plural': '商品SKU',
                'db_table': 'product_item',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(verbose_name='订单ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('images', models.TextField(blank=True, verbose_name='评论图片(JSON)')),
                ('rating', models.SmallIntegerField(default=5, verbose_name='评分(1-5)')),
                ('comment_level', models.SmallIntegerField(choices=[(1, '差评'), (2, '中评'), (3, '好评')], default=3, verbose_name='评价等级')),
                ('reply_content', models.TextField(blank=True, verbose_name='商家回复')),
                ('reply_time', models.DateTimeField(blank=True, null=True, verbose_name='回复时间')),
                ('helpful_count', models.IntegerField(default=0, verbose_name='有用数')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品评论',
                'verbose_name_plural': '商品评论',
                'db_table': 'product_comment',
                'ordering': ['-created_time'],
            },
        ),
    ]
